apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp-crds
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp-crds
  releaseName: openmfp-crds
  values:
    imagePullSecret: ghcr-credentials
