apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-crd-gateway
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: example-crd-gateway
  releaseName: example-crd-gateway
  values:
    image:
      imagePullSecret: ghcr-credentials # TODO: temporary as long as the repo is private
    istio:
      enabled: false
