apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-crd-gateway
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: example-crd-gateway
  releaseName: example-crd-gateway
  values:
    image:
      imagePullSecret: ghcr-credentials
    virtualService:
      hosts:
        - "*"
    trust:
      openmfp:
        audience: openmfp
        allowedUsers: "*"
        oidcClient: openmfp
        trustedIssuer: http://localhost:8000/keycloak/realms/master
