version = 1
SPDX-PackageName = "openmfp"
SPDX-PackageDownloadLocation = "https://github.com/openmfp/openmfp"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and openMFP contributors and openmfp contributors."
SPDX-License-Identifier = "Apache-2.0"
