apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../infrastructure/controllers
- ../../apps/base/crds
# - ../../apps/base/authorization-webhook
# - ../../apps/base/account-ui
- ../../apps/base/openmfp

