apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: openmfp-system
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.0
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_PROXY_HEADERS
              value: "forwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/keycloak"
            - name: KC_LOG_LEVEL
              value: "DEBUG"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /keycloak/realms/master
              port: 8080