# Role that allows creating secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openmfp-system
  name: secret-creator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]

---
# RoleBinding that assigns the secret-creator role to the keycloak-client-creation service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-binding
  namespace: openmfp-system
subjects:
  - kind: ServiceAccount
    name: keycloak-client-creation
    namespace: openmfp-system
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io