apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: openmfp-system
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: keycloak
  releaseName: keycloak
  values:
    keycloak:
      httpRelativePath: "/keycloak/"
      logging:
        level: DEBUG
      auth:
        adminUser: keycloak-admin
        existingSecret: keycloak-admin
        passwordSecretKey: secret
      resourcesPreset: none
      postgresql:
        primary:
          resourcesPreset: none
          persistence:
            enabled: false
        auth:
          existingSecret: ""
          secretKeys:
            userPasswordKey: ""
            adminPasswordKey: ""
    keycloakConfig:
      url: http://keycloak.openmfp-system.svc.cluster.local/keycloak
      redirectUrls: [ "http://localhost/callback*" ]
    domain:
      pathPrefix: "/keycloak"
    imagePullSecrets: "ghcr-credentials"
    externalSecrets:
      enabled: false
    service:
      port: 80
      name: keycloak
    istio:
      virtualservice:
        hosts: [ "*" ]
      https:
        enabled: false
    job:
      annotations:
        "helm.sh/hook": post-install
        "helm.sh/hook-delete-policy": before-hook-creation
