apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-crd-gateway
  namespace: openmfp-system
spec:
  values:
    trust:
      openmfp:
        audience: openmfp
        allowedUsers: "*"
        oidcClient: openmfp
        trustedIssuer: https://auth.d1.openmfp.dxp.k8s.ondemand.com/realms/master
        jwksUrl: https://auth.d1.openmfp.dxp.k8s.ondemand.com/realms/master/protocol/openid-connect/certs

