clusters:
  - name: webhook
    cluster:
      certificate-authority: /config/ca.crt
      server: https://iam-authorization-webhook:9443/authz
users:
  - name: api-server
    user:
      token: test-token
current-context: webhook
contexts:
  - context:
      cluster: webhook
      user: api-server
    name: webhook
