apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iam-authorization-webhook
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: iam-authorization-webhook
  releaseName: iam-authorization-webhook
  values:
    imagePullSecrets: ghcr-credentials
    openfga:
      url: openmfp-openfga:8081
      storeName: test
    extraVolumeMounts:
    - name: rules-config
      mountPath: /var/data/rules
    extraVolumes:
    - name: rules-config
      configMap:
        name: webhook-rules

    extraEnvs:
    - name: WEBHOOK_AUDIENCE
      value: foo
    useInClusterClient: true
