apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: account-operator
  namespace: openmfp-system
spec:
  interval: 10m0s
  component: github.com/openmfp/account-operator
  repository:
    url: ghcr.io/openmfp/ocm
    secretRef:
        name: ghcr-credentials
  version:
    semver: "0.31.0"
---
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: account-operator-chart
  namespace: openmfp-system
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: account-operator
    namespace: openmfp-system
    resourceRef:
      name: chart
      version: 0.31.0
      extraIdentity:
        helmChart: account-operator
---
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: account-operator-image
  namespace: openmfp-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: account-operator
    namespace: openmfp-system
    resourceRef:
      name: image
      version: 0.31.0

---
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: account-operator-deployer
  namespace: openmfp-system
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: account-operator-chart
  helmReleaseTemplate:
    interval: 10s
    releaseName: account-operator
    targetNamespace: openmfp-system

