apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: account-operator
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: account-operator
  releaseName: account-operator
  values:
    imagePullSecret: ghcr-credentials
