apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: account-operator
  namespace: openmfp-system
spec:
  interval: 5m
  url: oci://ghcr.io/openmfp/account-operator/helm/account-operator
  ref:
    semver: "*"
