apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portal
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: portal
  releaseName: portal
  values:
    http:
      protocol: http
    image:
      pullSecret: ghcr-credentials # TODO: temporary as long as the repo is private
    istio:
      enabled: false
    externalSecrets:
      enabled: false
    trust:
      openmfp:
        baseDomains: "localhost"
        authDomain: http://localhost:8080/keycloak/realms/master/protocol/openid-connect
        tokenUrl: http://keycloak:8080/keycloak/realms/master/protocol/openid-connect/token
        oidcClientSecretName: openmfp-client
        loginAudience: openmfp
    frontendPort: 8080