apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp
  releaseName: openmfp
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
  values:
    imagePullSecret: ghcr-credentials
    example-resources:
      contentConfigurations:
        providers: true
