---
apiVersion: v1
kind: Namespace
metadata:
  name: ocm-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ocm-controller
  namespace: ocm-system
spec:
  interval: 24h
  url: oci://ghcr.io/open-component-model/helm/ocm-controller
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocm-controller
  namespace: ocm-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ocm-controller
  releaseName: ocm-controller
