apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
  namespace: openmfp-system
spec:
  interval: 5m
  chart:
    spec:
      chart: openfga
      sourceRef:
        kind: HelmRepository
        name: openfga
      version: "*"
  releaseName: openfga
    
