apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: account-operator-crds
  namespace: openmfp-system
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chartRef:
    kind: OCIRepository
    name: account-operator-crds
  releaseName: account-operator-crds
