apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio.yaml
  - extension-content-operator-crds-ocirepository.yaml
  - extension-content-operator-crds-helmrelease.yaml
#  - openmfp-ocirepository.yaml
#  - openmfp-helmrelease.yaml
